from mtm.components.meta_crawler import MetaCrawler
from mtm.components.extraction import get_url_formatter

if __name__ == "__main__":
    meta_crawler = MetaCrawler()
    playlist = meta_crawler.retrieve_playlist(
        "https://www.youtube.com/watch?v=1ZrOxeEn3Xk&list=PLnxumiKJyo1BXn2IWDx0gd7p9KzE4zAXy"
    )
    print(playlist)
    formatter = get_url_formatter("youtube")
    for item in playlist:
        print('"%s",' % formatter.get_playable_url(item))

all_ = [
    "https://www.youtube.com/watch?v=4ugMwV6JKXE",
    "https://www.youtube.com/watch?v=J7OSA6Kw2-s",
    "https://www.youtube.com/watch?v=luRkeDCoxZ4",
    "https://www.youtube.com/watch?v=2DUWs4WO__Y",
    "https://www.youtube.com/watch?v=gmar4gh5nIw",
    "https://www.youtube.com/watch?v=aJaZc4E8Y4U",
    "https://www.youtube.com/watch?v=CU2777IVMGU",
    "https://www.youtube.com/watch?v=IvjMgVS6kng",
    "https://www.youtube.com/watch?v=DEqgTkRMYso",
    "https://www.youtube.com/watch?v=CxQByCIzZ64",
    "https://www.youtube.com/watch?v=JAKdceOziLM",
    "https://www.youtube.com/watch?v=r2EXpMHEtB8",
    "https://www.youtube.com/watch?v=9JRQkrNwXKo",
    "https://www.youtube.com/watch?v=ed3DnP2nbrw",
    "https://www.youtube.com/watch?v=lT8lT1sjxVk",
    "https://www.youtube.com/watch?v=j61cl69MgIM",
    "https://www.youtube.com/watch?v=AXVTYeFDbuM",
    "https://www.youtube.com/watch?v=usAAuGIBZTg",
    "https://www.youtube.com/watch?v=lz6yCQBWSU8",
    "https://www.youtube.com/watch?v=_1n5_HknzTo",
    "https://www.youtube.com/watch?v=YkXOLiZLFho",
    "https://www.youtube.com/watch?v=HmCm3kgyFks",
    "https://www.youtube.com/watch?v=VhuaXzsm_O0",
    "https://www.youtube.com/watch?v=ebnVse36UhY",
    "https://www.youtube.com/watch?v=Jwhss4LOGE0",
    "https://www.youtube.com/watch?v=6xpqNMfRnUc",
    "https://www.youtube.com/watch?v=S7R_h1qRc2E",
    "https://www.youtube.com/watch?v=aewgrdzblJk",
    "https://www.youtube.com/watch?v=SUabnM-0We4",
    "https://www.youtube.com/watch?v=MwA8rmwoLvE",
    "https://www.youtube.com/watch?v=sVld3uKBMzE",
    "https://www.youtube.com/watch?v=Eqp0d-Uoeqk",
    "https://www.youtube.com/watch?v=HHKpPEMxNpw",
    "https://www.youtube.com/watch?v=cWU1o-misXI",
    "https://www.youtube.com/watch?v=T1LGw7PVHrU",
    "https://www.youtube.com/watch?v=Yol5fROT890",
    "https://www.youtube.com/watch?v=mApstMXkhbw",
    "https://www.youtube.com/watch?v=h5UpkFgpkCE",
    "https://www.youtube.com/watch?v=4ugMwV6JKXE",
    "https://www.youtube.com/watch?v=LEixnEKdwTM",
    "https://www.youtube.com/watch?v=lT8lT1sjxVk",
    "https://www.youtube.com/watch?v=AXVTYeFDbuM",
    "https://www.youtube.com/watch?v=usAAuGIBZTg",
    "https://www.youtube.com/watch?v=lz6yCQBWSU8",
    "https://www.youtube.com/watch?v=_1n5_HknzTo",
    "https://www.youtube.com/watch?v=YkXOLiZLFho",
    "https://www.youtube.com/watch?v=HmCm3kgyFks",
    "https://www.youtube.com/watch?v=VhuaXzsm_O0",
    "https://www.youtube.com/watch?v=ebnVse36UhY",
    "https://www.youtube.com/watch?v=6xpqNMfRnUc",
    "https://www.youtube.com/watch?v=S7R_h1qRc2E",
    "https://www.youtube.com/watch?v=aewgrdzblJk",
    "https://www.youtube.com/watch?v=SUabnM-0We4",
    "https://www.youtube.com/watch?v=MwA8rmwoLvE",
    "https://www.youtube.com/watch?v=Eqp0d-Uoeqk",
    "https://www.youtube.com/watch?v=HHKpPEMxNpw",
    "https://www.youtube.com/watch?v=mApstMXkhbw",
    "https://www.youtube.com/watch?v=twu-3JzD-RI",
    "https://www.youtube.com/watch?v=3ynRsI5wtDo",
    "https://www.youtube.com/watch?v=SVqaafea7WA",
    "https://www.youtube.com/watch?v=1ZrOxeEn3Xk",
    "https://www.youtube.com/watch?v=ghzxtpkgRX8",
    "https://www.youtube.com/watch?v=CU2777IVMGU",
    "https://www.youtube.com/watch?v=r2EXpMHEtB8",
    "https://www.youtube.com/watch?v=ed3DnP2nbrw",
    "https://www.youtube.com/watch?v=J7OSA6Kw2-s",
    "https://www.youtube.com/watch?v=j61cl69MgIM",
    "https://www.youtube.com/watch?v=DEqgTkRMYso",
    "https://www.youtube.com/watch?v=AXVTYeFDbuM",
    "https://www.youtube.com/watch?v=usAAuGIBZTg",
    "https://www.youtube.com/watch?v=lz6yCQBWSU8",
    "https://www.youtube.com/watch?v=_1n5_HknzTo",
    "https://www.youtube.com/watch?v=YkXOLiZLFho",
    "https://www.youtube.com/watch?v=HmCm3kgyFks",
    "https://www.youtube.com/watch?v=VhuaXzsm_O0",
    "https://www.youtube.com/watch?v=ebnVse36UhY",
    "https://www.youtube.com/watch?v=aewgrdzblJk",
    "https://www.youtube.com/watch?v=SUabnM-0We4",
    "https://www.youtube.com/watch?v=sVld3uKBMzE",
    "https://www.youtube.com/watch?v=cWU1o-misXI",
    "https://www.youtube.com/watch?v=T1LGw7PVHrU",
    "https://www.youtube.com/watch?v=Yol5fROT890",
    "https://www.youtube.com/watch?v=mApstMXkhbw",
    "https://www.youtube.com/watch?v=twu-3JzD-RI",
    "https://www.youtube.com/watch?v=3ynRsI5wtDo",
]
